name: launch_app_store
description: A Flutter plugin to reviews in Google Play Store and Apple App Store.
version: 1.0.1
homepage: https://github.com/euferreira/launch_review

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.iyaffle.launchreview
        pluginClass: LaunchReviewPlugin
      ios:
        pluginClass: LaunchReviewPlugin

environment:  
  sdk: ">=2.17.5 <3.0.0"
